----QUESTION 1------
SELECT FIRST_NAME FROM SALES.CUSTOMERS ORDER BY FIRST_NAME DESC

----QUESTION 2-----------
SELECT FIRST_NAME,LAST_NAME,CITY FROM SALES.CUSTOMERS ORDER BY CITY,FIRST_NAME

---QUESTION 3-------------
SELECT TOP(3) LIST_PRICE,product_name FROM PRODUCTION.PRODUCTS ORDER BY LIST_PRICE DESC

---QUESTION 4-------------
SELECT PRODUCT_NAME,LIST_PRICE,MODEL_YEAR FROM PRODUCTION.PRODUCTS WHERE LIST_PRICE>300 AND MODEL_YEAR=2018

---QUESTION 5-------------
SELECT PRODUCT_NAME,LIST_PRICE,MODEL_YEAR FROM PRODUCTION.PRODUCTS WHERE LIST_PRICE>3000 OR MODEL_YEAR=2018

---QUESTION 6-------------
SELECT PRODUCT_NAME,LIST_PRICE FROM PRODUCTION.PRODUCTS WHERE LIST_PRICE>=1899 AND LIST_PRICE<=1999.99

---QUESTION 7-------------
SELECT PRODUCT_NAME,LIST_PRICE FROM PRODUCTION.PRODUCTS WHERE LIST_PRICE IN(299.99,466.99,489.99)

---QUESTION 8-------------
SELECT LAST_NAME FROM SALES.CUSTOMERS WHERE LAST_NAME LIKE '[ABC]%'

---QUESTION 9-------------
SELECT FIRST_NAME FROM SALES.CUSTOMERS WHERE FIRST_NAME NOT LIKE 'A%'

---QUESTION 10-------------
SELECT CITY,STATE, COUNT (CUSTOMER_ID) AS CUSTOMER_NUM FROM SALES.CUSTOMERS GROUP BY CITY,STATE

---QUESTION 11-------------
SELECT  COUNT (ORDER_ID) AS NUM_ORDERS FROM SALES.ORDERS GROUP BY CUSTOMER_ID,YEAR(ORDER_DATE)


---QUESTION 12-------------
SELECT CATEGORY_ID, MAX(LIST_PRICE),MIN(LIST_PRICE) FROM PRODUCTION.PRODUCTS GROUP BY category_id HAVING MAX(LIST_PRICE)>4000 OR MIN(LIST_PRICE)<500
